// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.epam.hack.choosebyspeed.web;

import com.epam.hack.choosebyspeed.domain.Category;
import com.epam.hack.choosebyspeed.domain.Provider;
import com.epam.hack.choosebyspeed.web.ProviderController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect ProviderController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ProviderController.create(@Valid Provider provider, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, provider);
            return "providers/create";
        }
        uiModel.asMap().clear();
        provider.persist();
        return "redirect:/providers/" + encodeUrlPathSegment(provider.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ProviderController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Provider());
        return "providers/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ProviderController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("provider", Provider.findProvider(id));
        uiModel.addAttribute("itemId", id);
        return "providers/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ProviderController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("providers", Provider.findProviderEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) Provider.countProviders() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("providers", Provider.findAllProviders(sortFieldName, sortOrder));
        }
        return "providers/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ProviderController.update(@Valid Provider provider, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, provider);
            return "providers/update";
        }
        uiModel.asMap().clear();
        provider.merge();
        return "redirect:/providers/" + encodeUrlPathSegment(provider.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ProviderController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, Provider.findProvider(id));
        return "providers/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ProviderController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Provider provider = Provider.findProvider(id);
        provider.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/providers";
    }
    
    void ProviderController.populateEditForm(Model uiModel, Provider provider) {
        uiModel.addAttribute("provider", provider);
        uiModel.addAttribute("categorys", Category.findAllCategorys());
    }
    
    String ProviderController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
