// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.epam.hack.choosebyspeed.domain;

import com.epam.hack.choosebyspeed.domain.Category;

privileged aspect Category_Roo_JavaBean {
    
    public String Category.getName() {
        return this.name;
    }
    
    public void Category.setName(String name) {
        this.name = name;
    }
    
    public Category Category.getParent() {
        return this.parent;
    }
    
    public void Category.setParent(Category parent) {
        this.parent = parent;
    }
    
}
