// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.epam.hack.choosebyspeed.domain;

import com.epam.hack.choosebyspeed.domain.Customer;

privileged aspect Customer_Roo_JavaBean {
    
    public String Customer.getName() {
        return this.name;
    }
    
    public void Customer.setName(String name) {
        this.name = name;
    }
    
    public String Customer.getEmail() {
        return this.email;
    }
    
    public void Customer.setEmail(String email) {
        this.email = email;
    }
    
    public String Customer.getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void Customer.setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    
    public String Customer.getAddress() {
        return this.address;
    }
    
    public void Customer.setAddress(String address) {
        this.address = address;
    }
    
}
