// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.epam.hack.choosebyspeed.domain;

import com.epam.hack.choosebyspeed.domain.Delivery;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Delivery_Roo_Json {
    
    public String Delivery.toJson() {
        return new JSONSerializer()
        .exclude("*.class").deepSerialize(this);
    }
    
    public String Delivery.toJson(String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").deepSerialize(this);
    }
    
    public static Delivery Delivery.fromJsonToDelivery(String json) {
        return new JSONDeserializer<Delivery>()
        .use(null, Delivery.class).deserialize(json);
    }
    
    public static String Delivery.toJsonArray(Collection<Delivery> collection) {
        return new JSONSerializer()
        .exclude("*.class").deepSerialize(collection);
    }
    
    public static String Delivery.toJsonArray(Collection<Delivery> collection, String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").deepSerialize(collection);
    }
    
    public static Collection<Delivery> Delivery.fromJsonArrayToDeliverys(String json) {
        return new JSONDeserializer<List<Delivery>>()
        .use("values", Delivery.class).deserialize(json);
    }
    
}
