// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.epam.hack.choosebyspeed.domain;

import com.epam.hack.choosebyspeed.domain.Customer;
import com.epam.hack.choosebyspeed.domain.Delivery;
import com.epam.hack.choosebyspeed.domain.Provider;
import java.util.Date;

privileged aspect Delivery_Roo_JavaBean {
    
    public Provider Delivery.getProvider() {
        return this.provider;
    }
    
    public void Delivery.setProvider(Provider provider) {
        this.provider = provider;
    }
    
    public Customer Delivery.getCustomer() {
        return this.customer;
    }
    
    public void Delivery.setCustomer(Customer customer) {
        this.customer = customer;
    }
    
    public Date Delivery.getTimeStart() {
        return this.timeStart;
    }
    
    public void Delivery.setTimeStart(Date timeStart) {
        this.timeStart = timeStart;
    }
    
    public Date Delivery.getTimeEnd() {
        return this.timeEnd;
    }
    
    public void Delivery.setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }
    
    public Float Delivery.getTimeDuration() {
        return this.timeDuration;
    }
    
    public void Delivery.setTimeDuration(Float timeDuration) {
        this.timeDuration = timeDuration;
    }
    
}
