// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.epam.hack.choosebyspeed.domain;

import com.epam.hack.choosebyspeed.domain.Category;
import com.epam.hack.choosebyspeed.domain.Product;

privileged aspect Product_Roo_JavaBean {
    
    public String Product.getName() {
        return this.name;
    }
    
    public void Product.setName(String name) {
        this.name = name;
    }
    
    public Category Product.getCategory() {
        return this.category;
    }
    
    public void Product.setCategory(Category category) {
        this.category = category;
    }
    
}
