// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.epam.hack.choosebyspeed.domain;

import com.epam.hack.choosebyspeed.domain.Promotion;
import java.util.Date;

privileged aspect Promotion_Roo_JavaBean {
    
    public String Promotion.getName() {
        return this.name;
    }
    
    public void Promotion.setName(String name) {
        this.name = name;
    }
    
    public String Promotion.getDescription() {
        return this.description;
    }
    
    public void Promotion.setDescription(String description) {
        this.description = description;
    }
    
    public Date Promotion.getPeriodStart() {
        return this.periodStart;
    }
    
    public void Promotion.setPeriodStart(Date periodStart) {
        this.periodStart = periodStart;
    }
    
    public Date Promotion.getPeriodEnd() {
        return this.periodEnd;
    }
    
    public void Promotion.setPeriodEnd(Date periodEnd) {
        this.periodEnd = periodEnd;
    }
    
}
