// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.epam.hack.choosebyspeed.domain;

import com.epam.hack.choosebyspeed.domain.Category;
import com.epam.hack.choosebyspeed.domain.Provider;

privileged aspect Provider_Roo_JavaBean {
    
    public String Provider.getName() {
        return this.name;
    }
    
    public void Provider.setName(String name) {
        this.name = name;
    }
    
    public Category Provider.getCategory() {
        return this.category;
    }
    
    public void Provider.setCategory(Category category) {
        this.category = category;
    }
    
    public Float Provider.getLocationLat() {
        return this.locationLat;
    }
    
    public void Provider.setLocationLat(Float locationLat) {
        this.locationLat = locationLat;
    }
    
    public Float Provider.getLocationLong() {
        return this.locationLong;
    }
    
    public void Provider.setLocationLong(Float locationLong) {
        this.locationLong = locationLong;
    }
    
    public String Provider.getImageUrl() {
        return this.imageUrl;
    }
    
    public void Provider.setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    
    public byte[] Provider.getImage() {
        return this.image;
    }
    
    public void Provider.setImage(byte[] image) {
        this.image = image;
    }
    
    public String Provider.getDescription() {
        return this.description;
    }
    
    public void Provider.setDescription(String description) {
        this.description = description;
    }
    
    public String Provider.getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void Provider.setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    
    public String Provider.getMenuHtml() {
        return this.menuHtml;
    }
    
    public void Provider.setMenuHtml(String menuHtml) {
        this.menuHtml = menuHtml;
    }
    
}
