// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.epam.hack.choosebyspeed.domain;

import com.epam.hack.choosebyspeed.domain.Provider;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Provider_Roo_Json {
    
    public String Provider.toJson() {
        return new JSONSerializer()
        .exclude("*.class").deepSerialize(this);
    }
    
    public String Provider.toJson(String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").deepSerialize(this);
    }
    
    public static Provider Provider.fromJsonToProvider(String json) {
        return new JSONDeserializer<Provider>()
        .use(null, Provider.class).deserialize(json);
    }
    
    public static String Provider.toJsonArray(Collection<Provider> collection) {
        return new JSONSerializer()
        .exclude("*.class").deepSerialize(collection);
    }
    
    public static String Provider.toJsonArray(Collection<Provider> collection, String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").deepSerialize(collection);
    }
    
    public static Collection<Provider> Provider.fromJsonArrayToProviders(String json) {
        return new JSONDeserializer<List<Provider>>()
        .use("values", Provider.class).deserialize(json);
    }
    
}
