// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.epam.hack.choosebyspeed.domain;

import com.epam.hack.choosebyspeed.domain.Provider;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Provider_Roo_Configurable {
    
    declare @type: Provider: @Configurable;
    
}
